name: 🧪 Test

on:
  workflow_call:
  push:
    branches-ignore:
      - master

jobs:
  test:
    runs-on: arc-runner-set
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      
      - name: Test
        shell: bash
        run: ./test/bats/bin/bats ./test
