name: 📦 Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
        type: string

jobs:
  test:
    uses: ./.github/workflows/test.yaml

  release:
    needs: test
    uses: cdqag/workflow-public/.github/workflows/release-action-to-branch.yaml@v1
    with:
      runs-on: ubuntu-latest
      version: ${{ inputs.version }}
